package com.xiutech.simix.modelo;
// Generated 29-mar-2019 11:00:45 by Hibernate Tools 4.3.1



/**
 * CalificacionId generated by hbm2java
 */
public class CalificacionId  implements java.io.Serializable {


     private int idMarcador;
     private String correoComentarista;
     private String correoCalificador;

    public CalificacionId() {
    }

    public CalificacionId(int idMarcador, String correoComentarista, String correoCalificador) {
       this.idMarcador = idMarcador;
       this.correoComentarista = correoComentarista;
       this.correoCalificador = correoCalificador;
    }
   
    public int getIdMarcador() {
        return this.idMarcador;
    }
    
    public void setIdMarcador(int idMarcador) {
        this.idMarcador = idMarcador;
    }
    public String getCorreoComentarista() {
        return this.correoComentarista;
    }
    
    public void setCorreoComentarista(String correoComentarista) {
        this.correoComentarista = correoComentarista;
    }
    public String getCorreoCalificador() {
        return this.correoCalificador;
    }
    
    public void setCorreoCalificador(String correoCalificador) {
        this.correoCalificador = correoCalificador;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CalificacionId) ) return false;
		 CalificacionId castOther = ( CalificacionId ) other; 
         
		 return (this.getIdMarcador()==castOther.getIdMarcador())
 && ( (this.getCorreoComentarista()==castOther.getCorreoComentarista()) || ( this.getCorreoComentarista()!=null && castOther.getCorreoComentarista()!=null && this.getCorreoComentarista().equals(castOther.getCorreoComentarista()) ) )
 && ( (this.getCorreoCalificador()==castOther.getCorreoCalificador()) || ( this.getCorreoCalificador()!=null && castOther.getCorreoCalificador()!=null && this.getCorreoCalificador().equals(castOther.getCorreoCalificador()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdMarcador();
         result = 37 * result + ( getCorreoComentarista() == null ? 0 : this.getCorreoComentarista().hashCode() );
         result = 37 * result + ( getCorreoCalificador() == null ? 0 : this.getCorreoCalificador().hashCode() );
         return result;
   }   


}


