package com.xiutech.simix.modelo;
// Generated 29-mar-2019 11:00:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Comentario generated by hbm2java
 */
public class Comentario  implements java.io.Serializable {


     private ComentarioId id;
     private Comentarista comentarista;
     private Marcador marcador;
     private String texto;
     private Set calificacions = new HashSet(0);

    public Comentario() {
    }

	
    public Comentario(ComentarioId id, Comentarista comentarista, Marcador marcador, String texto) {
        this.id = id;
        this.comentarista = comentarista;
        this.marcador = marcador;
        this.texto = texto;
    }
    public Comentario(ComentarioId id, Comentarista comentarista, Marcador marcador, String texto, Set calificacions) {
       this.id = id;
       this.comentarista = comentarista;
       this.marcador = marcador;
       this.texto = texto;
       this.calificacions = calificacions;
    }
   
    public ComentarioId getId() {
        return this.id;
    }
    
    public void setId(ComentarioId id) {
        this.id = id;
    }
    public Comentarista getComentarista() {
        return this.comentarista;
    }
    
    public void setComentarista(Comentarista comentarista) {
        this.comentarista = comentarista;
    }
    public Marcador getMarcador() {
        return this.marcador;
    }
    
    public void setMarcador(Marcador marcador) {
        this.marcador = marcador;
    }
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }
    public Set getCalificacions() {
        return this.calificacions;
    }
    
    public void setCalificacions(Set calificacions) {
        this.calificacions = calificacions;
    }




}


