package com.xiutech.simix.modelo;
// Generated 29-mar-2019 11:00:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Informador generated by hbm2java
 */
public class Informador  implements java.io.Serializable {


     private String correo;
     private String nombre;
     private String contrasenia;
     private Set temas = new HashSet(0);

    public Informador() {
    }

	
    public Informador(String correo, String nombre, String contrasenia) {
        this.correo = correo;
        this.nombre = nombre;
        this.contrasenia = contrasenia;
    }
    public Informador(String correo, String nombre, String contrasenia, Set temas) {
       this.correo = correo;
       this.nombre = nombre;
       this.contrasenia = contrasenia;
       this.temas = temas;
    }
   
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public Set getTemas() {
        return this.temas;
    }
    
    public void setTemas(Set temas) {
        this.temas = temas;
    }




}


