package com.xiutech.simix.modelo;
// Generated 29-mar-2019 11:00:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tema generated by hbm2java
 */
public class Tema  implements java.io.Serializable {


     private String nombre;
     private Informador informador;
     private String color;
     private Set marcadors = new HashSet(0);

    public Tema() {
    }

	
    public Tema(String nombre, String color) {
        this.nombre = nombre;
        this.color = color;
    }
    public Tema(String nombre, Informador informador, String color, Set marcadors) {
       this.nombre = nombre;
       this.informador = informador;
       this.color = color;
       this.marcadors = marcadors;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Informador getInformador() {
        return this.informador;
    }
    
    public void setInformador(Informador informador) {
        this.informador = informador;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public Set getMarcadors() {
        return this.marcadors;
    }
    
    public void setMarcadors(Set marcadors) {
        this.marcadors = marcadors;
    }




}


